### ISSUE TITLE
Search is slow and results unclear

### ISSUE THREAD

**Issue by chrisgilmerproj** [robdmc/gistfinder#5]
I didn't look into your search algorithm setup but my experience is that the search bogs up pretty quickly. I searched for the word `session` in my gists. It seemed to kick off the search before I was done typing, which makes me think you might want to introduce a delay to see if typing has finished. I may be seeing an issue where the gists I have are incredibly long with log output from incidents I've fixed in the past.

It's not super apparent where the files are that have matches. I think it resorts the gists by hits, but a visual indicator like a `*` would be nice or even highlighting the files differently.

**Comment by Akagi201** [comment]
hope to write a golang version
